# Generated by Django 2.0.7 on 2019-02-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='totalmarks',
            field=models.IntegerField(default=-1),
        ),
    ]
